### ISSUE TITLE
Account Signup Process

### ISSUE THREAD

**Issue by davidjeddy** [davidjeddy/naabs2#7]
{FE app}/site/signup not logged in:

Add secondary phone number field (optional)
Add Lot Number as a field (optional)
Remove Username, Primary email will be username. Move Email to the top field
Remove Secondary email

Add red stars next to required field names

When submit is clicked and things are applied to the DB. Take them to a new view. (currently goes back to index), 

Header:
Account Creation was a success!

Body:
You are Almost Done (subheader)

It is very important to keep the information you used to create this account. We recommend that you write it down and save it somewhere in a safe place. Even if you call us we will need ask you this information for security purposes.

User Email:
Security Question:
Answer:

Remember your user email is your username for logging into the portal for internet, and the account management page.

Now that your account has been created you must add a block of time to your account before you can go online. To add time please go to the Purchase Page. (make "Purchase Page" a link to http://10.3.2.111/frontend/web/index.php/purchase/create)

Button <Purchase Time> (takes you to the purchase page as well)

**Comment by davidjeddy** [comment]
Removing username in favor of using primary email as username has a problem: in the FreeRadius system the username is used to idtenty each device
`UserUsername 1`,  `UserUsername  2` and two devices assigned to the user `UserUsername`.

This needs thought out more.

**Comment by guitarboy8d6** [comment]
I see issue as well, this is more for end user ability could we do email@domain.com-1 and then -2 and so one for device usernames? Or allow them to create a friendly username for the device names? There also may need to be some wording changes around what I previously sent over as well. As is does it auto assign username and pw, per device or does the system autogenerate each. I never got to that part of the work flow. And other ticket states managing deivce area maybe a hold off till V3.

**Comment by guitarboy8d6** [comment]
After further review and experimentation in the admin area, I think the way we need to think about the hierarchy of a user to a device. 

This is probably part of a core change, that would happen at sign up, in the admin area and several other areas in the way we handle users and devices.

The full feature request would be 
User has multiple devices, of devices they could have two types, normal like we are used to and already setup for and then streaming devices. We should store and show some type of friendly name like device used, or nickname or something like that. The user should be able to control the devices independently. I am envisioning a grid view where they could add, edit or remove a device. Based on device type the system would handle how it gets put into the radcheck table and how it stores to the different databases and tables and displays later on. On streaming devices we would have to have the user put in the mac of the device. That way the RAIDUS and NAS can recognize the device with out submitting data to a form through a web browser.

The expire time would be the same on every device, because the time purchase is tied to the user, not the device. In the database and backend operation of the site/code I realize each device has its own expire time field, but to the front end and user, not so. 

Even if we hadn't decided to change the model where we charge a upgrade fee to have more than 3 devices like originally requested, the fee was just on the device, but the amount of time and fee charge should be calculated on the users time, so if they were renewing for a month and had 2 extra devices, it would be the monthly fee, plus the 2 extra device charges for the month. Which I get we would have to define the devices charges on the same time periods, or we could put a base time in to where the system calculates it, so if the device upcharge is $5 a device for a month and they want to add a device but have 20 days left of the month, the system could do the math to prorate it. And when they added time, the system would calculate the up charge by checking how many devices are on the account.

Since we decided though to just cap and 5 and go away from the above described model to a no up charge model per device it has been stated that this should be more of a version 3 request. However the current model of sign up and adding devices doesn't seem to represent what was described above either. 

Because of the Radius and Network Authentication Server each device does need its own username and pw. This implementation is being setup for old people that sometimes don't even realize what there email address is. But we have a better chance of them knowing there email address than some additional username. Making the primary email address, primary login as well would help with support these users on the long haul.

Now how we define username by device we could force a variation of username like the described above where we take primary email and add a -1, -2, etc. Or come up with something else. I realize it maybe a security concern, but keeping all of them with the same password would be something I would like to investigate the pros and cons of as well. Because I have to make support as easy as possible. But I do see the possible security issues.

Not sure how this helps this specific ticket, because it seems like this effects several area's/tickets and isn't really a bug, but a workflow/system design issue.

What are your thoughts on this.

**Comment by davidjeddy** [comment]
ADDED 2ndary phone to sign up form
WILL NOT remove username in place of primary email (v3 design)
ADDED red \* to indicate required fields
ADDED signup-complete VW for signup process completion

Please file issues as separate tickets in the futures. bug/feature/enhancement/etc
